name: sdcvault
version: 0.0.1
require-dbt-version: [">=1.0.0", "<2.0.0"]
config-version: 2

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
docs-paths: ["docs"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  sdcvault.high_water_mark: true
  sdvault.natural_key: false
  sdcvault.ghost_hk: "'00000000000000000000000000000000'"
  sdcvault.ghost_ts: "'1900-01-01'"
  sdcvault.ghost_source: "'System'"