{%- macro prepend_generated_by() -%}
    {{ adapter.dispatch('prepend_generated_by', 'sdcvault')() -}}
{%- endmacro -%}

{%- macro default__prepend_generated_by() -%}
-- Code generated by sdcvault
{%- endmacro -%}